// Auto generated by ./transform.js
using System.Text.RegularExpressions;
using WebSpark.PrismSpark;

namespace WebSpark.PrismSpark.Languages;

// From https://github.com/PrismJS/prism/blob/master/components/prism-java.js

/// <summary>
/// Provides syntax highlighting grammar definition for the Java programming language.
/// Supports Java syntax including doc comments, annotations, generics, keywords, and class/method definitions.
/// </summary>
public class Java : IGrammarDefinition
{
  /// <summary>
  /// Defines the grammar rules for Java syntax highlighting.
  /// </summary>
  /// <returns>A Grammar object containing the token definitions for Java language syntax.</returns>
  public Grammar Define()
  {
    var grammar = new Grammar();

    grammar["doc-comment"] = new GrammarToken[]
    {

        new(@"(^|[^\\])\/\*\*[^/][\s\S]*?(?:\*\/|$)", lookbehind: true, greedy: false, alias: new []{"comment" }, inside: new Grammar
  {
      Reset = new Grammar
  {
      ["parameter"] = new GrammarToken[]
      {

        new(new Regex(@"(^[\t ]*(?:\/{3}|\*|\/\*\*)\s*@(?:arg|arguments|param)\s+)\w+", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: false),
      },
      ["reference"] = new GrammarToken[]
      {

        new(@"(@(?:exception|link|linkplain|see|throws|value)\s+(?:\*\s*)?)(?:(?:\b[a-zA-Z]\w+\s*\.\s*)*\b[A-Z]\w*(?:\s*#\s*\w+(?:\s*\([^()]*\))?)?|#\s*\w+(?:\s*\([^()]*\))?)", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["function"] = new GrammarToken[]
      {

        new(@"(#\s*)\w+(?=\s*\()", lookbehind: true, greedy: false),
      },
      ["field"] = new GrammarToken[]
      {

        new(@"(#\s*)\w+", lookbehind: true, greedy: false),
      },
      ["namespace"] = new GrammarToken[]
      {

        new(@"\b(?:[a-z]\w*\s*\.\s*)+", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
  }),
      },
      ["class-name"] = new GrammarToken[]
      {

        new(@"\b[A-Z]\w*", lookbehind: false, greedy: false),
      },
      ["keyword"] = new GrammarToken[]
      {

        new(@"\b(?:abstract|assert|boolean|break|byte|case|catch|char|class|const|continue|default|do|double|else|enum|exports|extends|final|finally|float|for|goto|if|implements|import|instanceof|int|interface|long|module|native|new|non-sealed|null|open|opens|package|permits|private|protected|provides|public|record(?!\s*[(){}[\]<>=%~.:,;?+\-*/&|^])|requires|return|sealed|short|static|strictfp|super|switch|synchronized|this|throw|throws|to|transient|transitive|try|uses|var|void|volatile|while|with|yield)\b", lookbehind: false, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[#()[\],.]", lookbehind: false, greedy: false),
      },
  }),
      },
      ["class-name"] = new GrammarToken[]
      {

        new(@"(@param\s+)<[A-Z]\w*>", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[.<>]", lookbehind: false, greedy: false),
      },
  }),
      },
      ["code-section"] = new GrammarToken[]
      {

        new(@"(\{@code\s+(?!\s))(?:[^\s{}]|\s+(?![\s}])|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\})*\})+(?=\s*\})", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["code"] = new GrammarToken[]
      {

        new(new Regex(@"(^(?:[\t ]*(?:\*\s*)*))[^*\s].*$", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: false, alias: new []{"language-java" }, inside: null! /* see below */),
      },
  }),
        new(@"(<(code|pre|tt)>(?!<code>)\s*)\S(?:\S|\s+\S)*?(?=\s*<\/\2>)", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["line"] = new GrammarToken[]
      {

        new(new Regex(@"(^(?:[\t ]*(?:\*\s*)*))[^*\s].*$", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: false, inside: new Grammar
  {
      ["tag"] = new GrammarToken[]
      {

        new(@"<\/?(?!\d)[^\s>\/=$<%]+(?:\s(?:\s*[^\s>\/=]+(?:\s*=\s*(?:""[^""]*""|'[^']*'|[^\s'"">=]+(?=[\s>]))|(?=[\s/>])))+)?\s*\/?>", lookbehind: false, greedy: true, inside: new Grammar
  {
      ["tag"] = new GrammarToken[]
      {

        new(@"^<\/?[^\s>\/]+", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"^<\/?", lookbehind: false, greedy: false),
      },
      ["namespace"] = new GrammarToken[]
      {

        new(@"^[^\s>\/:]+:", lookbehind: false, greedy: false),
      },
  }),
      },
      ["special-attr"] = new GrammarToken[]
      {

        new(new Regex(@"(^|[""'\s])(?:style)\s*=\s*(?:""[^""]*""|'[^']*'|[^\s'"">=]+(?=[\s>]))", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false, inside: new Grammar
  {
      ["attr-name"] = new GrammarToken[]
      {

        new(@"^[^\s=]+", lookbehind: false, greedy: false),
      },
      ["attr-value"] = new GrammarToken[]
      {

        new(@"=[\s\S]+", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["value"] = new GrammarToken[]
      {

        new(@"(^=\s*([""']|(?![""'])))\S[\s\S]*(?=\2$)", lookbehind: true, greedy: false, alias: new []{"css , language-css" }, inside: new Grammar
  {
      ["comment"] = new GrammarToken[]
      {

        new(@"\/\*[\s\S]*?\*\/", lookbehind: false, greedy: false),
      },
      ["atrule"] = new GrammarToken[]
      {

        new(@"@[\w-](?:[^;{\s]|\s+(?![\s{]))*(?:;|(?=\s*\{))", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["rule"] = new GrammarToken[]
      {

        new(@"^@[\w-]+", lookbehind: false, greedy: false),
      },
      ["selector-function-argument"] = new GrammarToken[]
      {

        new(@"(\bselector\s*\(\s*(?![\s)]))(?:[^()\s]|\s+(?![\s)])|\((?:[^()]|\([^()]*\))*\))+(?=\s*\))", lookbehind: true, greedy: false, alias: new []{"selector" }, inside: new Grammar
  {
      ["pseudo-element"] = new GrammarToken[]
      {

        new(@":(?:after|before|first-letter|first-line|selection)|::[-\w]+", lookbehind: false, greedy: false),
      },
      ["pseudo-class"] = new GrammarToken[]
      {

        new(@":[-\w]+", lookbehind: false, greedy: false),
      },
      ["class"] = new GrammarToken[]
      {

        new(@"\.[-\w]+", lookbehind: false, greedy: false),
      },
      ["id"] = new GrammarToken[]
      {

        new(@"#[-\w]+", lookbehind: false, greedy: false),
      },
      ["attribute"] = new GrammarToken[]
      {

        new(@"\[(?:[^[\]""']|(""|')(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1)*\]", lookbehind: false, greedy: true, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"^\[|\]$", lookbehind: false, greedy: false),
      },
      ["case-sensitivity"] = new GrammarToken[]
      {

        new(new Regex(@"(\s)[si]$", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false, alias: new []{"keyword" }),
      },
      ["namespace"] = new GrammarToken[]
      {

        new(@"^(\s*)(?:(?!\s)[-*\w\xA0-\uFFFF])*\|(?!=)", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\|$", lookbehind: false, greedy: false),
      },
  }),
      },
      ["attr-name"] = new GrammarToken[]
      {

        new(@"^(\s*)(?:(?!\s)[-\w\xA0-\uFFFF])+", lookbehind: true, greedy: false),
      },
      ["attr-value"] = new GrammarToken[]
      {

        new(@"(""|')(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1", lookbehind: false, greedy: false),
        new(@"(=\s*)(?:(?!\s)[-\w\xA0-\uFFFF])+(?=\s*$)", lookbehind: true, greedy: false),
      },
      ["operator"] = new GrammarToken[]
      {

        new(@"[|~*^$]?=", lookbehind: false, greedy: false),
      },
  }),
      },
      ["n-th"] = new GrammarToken[]
      {

        new(@"(\(\s*)[+-]?\d*[\dn](?:\s*[+-]\s*\d+)?(?=\s*\))", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["number"] = new GrammarToken[]
      {

        new(@"[\dn]+", lookbehind: false, greedy: false),
      },
      ["operator"] = new GrammarToken[]
      {

        new(@"[+-]", lookbehind: false, greedy: false),
      },
  }),
        new(new Regex(@"(\(\s*)(?:even|odd)(?=\s*\))", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false),
      },
      ["combinator"] = new GrammarToken[]
      {

        new(@">|\+|~|\|\|", lookbehind: false, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[(),]", lookbehind: false, greedy: false),
      },
  }),
      },
      ["keyword"] = new GrammarToken[]
      {

        new(@"(^|[^\w-])(?:and|not|only|or)(?![\w-])", lookbehind: true, greedy: false),
      },
      Reset = null! /* see below */,
  }),
      },
      ["url"] = new GrammarToken[]
      {

        new(new Regex(@"\burl\((?:(?:""(?:\\(?:\r\n|[\s\S])|[^""\\\r\n])*""|'(?:\\(?:\r\n|[\s\S])|[^'\\\r\n])*')|(?:[^\\\r\n()""']|\\[\s\S])*)\)", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: true, inside: new Grammar
  {
      ["function"] = new GrammarToken[]
      {

        new(new Regex(@"^url", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"^\(|\)$", lookbehind: false, greedy: false),
      },
      ["string"] = new GrammarToken[]
      {

        new(@"^(?:""(?:\\(?:\r\n|[\s\S])|[^""\\\r\n])*""|'(?:\\(?:\r\n|[\s\S])|[^'\\\r\n])*')$", lookbehind: false, greedy: false, alias: new []{"url" }),
      },
  }),
      },
      ["selector"] = new GrammarToken[]
      {

        new(@"(^|[{}\s])[^{}\s](?:[^{};""'\s]|\s+(?![\s{])|(?:""(?:\\(?:\r\n|[\s\S])|[^""\\\r\n])*""|'(?:\\(?:\r\n|[\s\S])|[^'\\\r\n])*'))*(?=\s*\{)", lookbehind: true, greedy: false, inside: null! /* see below */),
      },
      ["string"] = new GrammarToken[]
      {

        new(@"(?:""(?:\\(?:\r\n|[\s\S])|[^""\\\r\n])*""|'(?:\\(?:\r\n|[\s\S])|[^'\\\r\n])*')", lookbehind: false, greedy: true),
      },
      ["variable"] = new GrammarToken[]
      {

        new(new Regex(@"(^|[^-\w\xA0-\uFFFF])--(?!\s)[-_a-z\xA0-\uFFFF](?:(?!\s)[-\w\xA0-\uFFFF])*", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false),
      },
      ["property"] = new GrammarToken[]
      {

        new(new Regex(@"(^|[^-\w\xA0-\uFFFF])(?!\s)[-_a-z\xA0-\uFFFF](?:(?!\s)[-\w\xA0-\uFFFF])*(?=\s*:)", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false),
      },
      ["important"] = new GrammarToken[]
      {

        new(new Regex(@"!important\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false),
      },
      ["operator"] = new GrammarToken[]
      {

        new(@"(\s)[+\-*\/](?=\s)", lookbehind: true, greedy: false),
      },
      ["hexcode"] = new GrammarToken[]
      {

        new(new Regex(@"\B#[\da-f]{3,8}\b", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false, alias: new []{"color" }),
      },
      ["color"] = new GrammarToken[]
      {

        new(new Regex(@"(^|[^\w-])(?:AliceBlue|AntiqueWhite|Aqua|Aquamarine|Azure|Beige|Bisque|Black|BlanchedAlmond|Blue|BlueViolet|Brown|BurlyWood|CadetBlue|Chartreuse|Chocolate|Coral|CornflowerBlue|Cornsilk|Crimson|Cyan|DarkBlue|DarkCyan|DarkGoldenRod|DarkGr[ae]y|DarkGreen|DarkKhaki|DarkMagenta|DarkOliveGreen|DarkOrange|DarkOrchid|DarkRed|DarkSalmon|DarkSeaGreen|DarkSlateBlue|DarkSlateGr[ae]y|DarkTurquoise|DarkViolet|DeepPink|DeepSkyBlue|DimGr[ae]y|DodgerBlue|FireBrick|FloralWhite|ForestGreen|Fuchsia|Gainsboro|GhostWhite|Gold|GoldenRod|Gr[ae]y|Green|GreenYellow|HoneyDew|HotPink|IndianRed|Indigo|Ivory|Khaki|Lavender|LavenderBlush|LawnGreen|LemonChiffon|LightBlue|LightCoral|LightCyan|LightGoldenRodYellow|LightGr[ae]y|LightGreen|LightPink|LightSalmon|LightSeaGreen|LightSkyBlue|LightSlateGr[ae]y|LightSteelBlue|LightYellow|Lime|LimeGreen|Linen|Magenta|Maroon|MediumAquaMarine|MediumBlue|MediumOrchid|MediumPurple|MediumSeaGreen|MediumSlateBlue|MediumSpringGreen|MediumTurquoise|MediumVioletRed|MidnightBlue|MintCream|MistyRose|Moccasin|NavajoWhite|Navy|OldLace|Olive|OliveDrab|Orange|OrangeRed|Orchid|PaleGoldenRod|PaleGreen|PaleTurquoise|PaleVioletRed|PapayaWhip|PeachPuff|Peru|Pink|Plum|PowderBlue|Purple|Red|RosyBrown|RoyalBlue|SaddleBrown|Salmon|SandyBrown|SeaGreen|SeaShell|Sienna|Silver|SkyBlue|SlateBlue|SlateGr[ae]y|Snow|SpringGreen|SteelBlue|Tan|Teal|Thistle|Tomato|Transparent|Turquoise|Violet|Wheat|White|WhiteSmoke|Yellow|YellowGreen)(?![\w-])", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false),
        new(new Regex(@"\b(?:hsl|rgb)\(\s*\d{1,3}\s*,\s*\d{1,3}%?\s*,\s*\d{1,3}%?\s*\)\B|\b(?:hsl|rgb)a\(\s*\d{1,3}\s*,\s*\d{1,3}%?\s*,\s*\d{1,3}%?\s*,\s*(?:0|0?\.\d+|1)\s*\)\B", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false, inside: new Grammar
  {
      ["unit"] = new GrammarToken[]
      {

        new(@"(\b\d+)(?:%|[a-z]+(?![\w-]))", lookbehind: true, greedy: false),
      },
      ["number"] = new GrammarToken[]
      {

        new(@"(^|[^\w.-])-?(?:\d+(?:\.\d+)?|\.\d+)", lookbehind: true, greedy: false),
      },
      ["function"] = new GrammarToken[]
      {

        new(@"[\w-]+(?=\()", lookbehind: false, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[(),]", lookbehind: false, greedy: false),
      },
  }),
      },
      ["entity"] = new GrammarToken[]
      {

        new(new Regex(@"\\[\da-f]{1,8}", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false),
      },
      ["unit"] = new GrammarToken[]
      {
        null! /* see below */
      },
      ["number"] = new GrammarToken[]
      {
        null! /* see below */
      },
      ["function"] = new GrammarToken[]
      {

        new(new Regex(@"(^|[^-a-z0-9])[-a-z0-9]+(?=\()", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[(){};:,]", lookbehind: false, greedy: false),
      },
  }),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"^=", lookbehind: false, greedy: false, alias: new []{"attr-equals" }),
        new(@"""|'", lookbehind: false, greedy: false),
      },
  }),
      },
  }),
        new(new Regex(@"(^|[""'\s])(?:on(?:abort|blur|change|click|composition(?:end|start|update)|dblclick|error|focus(?:in|out)?|key(?:down|up)|load|mouse(?:down|enter|leave|move|out|over|up)|reset|resize|scroll|select|slotchange|submit|unload|wheel))\s*=\s*(?:""[^""]*""|'[^']*'|[^\s'"">=]+(?=[\s>]))", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false, inside: new Grammar
  {
      ["attr-name"] = new GrammarToken[]
      {

        new(@"^[^\s=]+", lookbehind: false, greedy: false),
      },
      ["attr-value"] = new GrammarToken[]
      {

        new(@"=[\s\S]+", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["value"] = new GrammarToken[]
      {

        new(@"(^=\s*([""']|(?![""'])))\S[\s\S]*(?=\2$)", lookbehind: true, greedy: false, alias: new []{"javascript , language-javascript" }, inside: new Grammar
  {
      ["doc-comment"] = new GrammarToken[]
      {

        new(@"(^|[^\\])\/\*\*[^/][\s\S]*?(?:\*\/|$)", lookbehind: true, greedy: false, alias: new []{"comment" }, inside: new Grammar
  {
      Reset = new Grammar
  {
      ["parameter"] = new GrammarToken[]
      {

        new(@"(@(?:arg|argument|param|property)\s+(?:\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})+\}\s+)?)(?:(?!\s)[$\w\xA0-\uFFFF.])+(?=\s|$)", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
  }),
      },
      ["optional-parameter"] = new GrammarToken[]
      {

        new(@"(@(?:arg|argument|param|property)\s+(?:\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})+\}\s+)?)\[(?:(?!\s)[$\w\xA0-\uFFFF.])+(?:=[^[\]]+)?\](?=\s|$)", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["parameter"] = new GrammarToken[]
      {

        new(@"(^\[)[$\w\xA0-\uFFFF\.]+", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
  }),
      },
      ["code"] = new GrammarToken[]
      {

        new(@"(=)[\s\S]*(?=\]$)", lookbehind: true, greedy: false, alias: new []{"language-javascript" }, inside: null! /* see below */),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[=[\]]", lookbehind: false, greedy: false),
      },
  }),
      },
      ["class-name"] = new GrammarToken[]
      {

        new(@"(@(?:augments|class|extends|interface|memberof!?|template|this|typedef)\s+(?:\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})+\}\s+)?)[A-Z]\w*(?:\.[A-Z]\w*)*", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
  }),
        new(@"(@[a-z]+\s+)\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})+\}", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["string"] = new GrammarToken[]
      {

        new(@"([""'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1", lookbehind: false, greedy: true),
      },
      ["number"] = new GrammarToken[]
      {

        new(@"(^|[^\w$])(?:NaN|Infinity|0[bB][01]+(?:_[01]+)*n?|0[oO][0-7]+(?:_[0-7]+)*n?|0[xX][\dA-Fa-f]+(?:_[\dA-Fa-f]+)*n?|\d+(?:_\d+)*n|(?:\d+(?:_\d+)*(?:\.(?:\d+(?:_\d+)*)?)?|\.\d+(?:_\d+)*)(?:[Ee][+-]?\d+(?:_\d+)*)?)(?![\w$])", lookbehind: true, greedy: false),
      },
      ["boolean"] = new GrammarToken[]
      {

        new(@"\b(?:false|true)\b", lookbehind: false, greedy: false),
      },
      ["keyword"] = new GrammarToken[]
      {

        new(@"((?:^|\})\s*)catch\b", lookbehind: true, greedy: false),
        new(@"(^|[^.]|\.\.\.\s*)\b(?:as|assert(?=\s*\{)|async(?=\s*(?:function\b|\(|[$\w\xA0-\uFFFF]|$))|await|break|case|class|const|continue|debugger|default|delete|do|else|enum|export|extends|finally(?=\s*(?:\{|$))|for|from(?=\s*(?:['""]|$))|function|(?:get|set)(?=\s*(?:[#\[$\w\xA0-\uFFFF]|$))|if|implements|import|in|instanceof|interface|let|new|null|of|package|private|protected|public|return|static|super|switch|this|throw|try|typeof|undefined|var|void|while|with|yield)\b", lookbehind: true, greedy: false),
        new(@"\b(?:abstract|declare|is|keyof|readonly|require)\b", lookbehind: false, greedy: false),
        new(@"\b(?:asserts|infer|interface|module|namespace|type)\b(?=\s*(?:[{_$a-zA-Z\xA0-\uFFFF]|$))", lookbehind: false, greedy: false),
        new(@"\btype\b(?=\s*(?:[\{*]|$))", lookbehind: false, greedy: false),
      },
      ["operator"] = new GrammarToken[]
      {

        new(@"=>|\.\.\.|[&|?:*]", lookbehind: false, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[.,;=<>{}()[\]]", lookbehind: false, greedy: false),
      },
  }),
      },
      ["example"] = new GrammarToken[]
      {

        new(@"(@example\s+(?!\s))(?:[^@\s]|\s+(?!\s))+?(?=\s*(?:\*\s*)?(?:@\w|\*\/))", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["code"] = new GrammarToken[]
      {

        new(new Regex(@"^([\t ]*(?:\*\s*)?)\S.*$", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: false, alias: new []{"language-javascript" }, inside: null! /* see below */),
      },
  }),
      },
      ["keyword"] = new GrammarToken[]
      {

        new(new Regex(@"(^[\t ]*(?:\/{3}|\*|\/\*\*)\s*|\{)@[a-z][a-zA-Z-]+\b", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[{}]", lookbehind: false, greedy: false),
      },
  },
  }),
      },
      ["comment"] = new GrammarToken[]
      {

        new(@"(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)", lookbehind: true, greedy: true),
        new(@"(^|[^\\:])\/\/.*", lookbehind: true, greedy: true),
      },
      ["hashbang"] = new GrammarToken[]
      {

        new(@"^#!.*", lookbehind: false, greedy: true, alias: new []{"comment" }),
      },
      ["template-string"] = new GrammarToken[]
      {

        new(@"((?:\b(?:styled(?:\([^)]*\))?(?:\s*\.\s*\w+(?:\([^)]*\))*)*|css(?:\s*\.\s*(?:global|resolve))?|createGlobalStyle|keyframes))\s*)`(?:\\[\s\S]|\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}|(?!\$\{)[^\\`])*`", lookbehind: true, greedy: true, inside: new Grammar
  {
      ["template-punctuation"] = new GrammarToken[]
      {

        new(@"^`|`$", lookbehind: false, greedy: false, alias: new []{"string" }),
      },
      ["embedded-code"] = new GrammarToken[]
      {

        new(@"[\s\S]+", lookbehind: false, greedy: false, alias: new []{"css" }),
      },
  }),
        new(@"((?:\bhtml|\.\s*(?:inner|outer)HTML\s*\+?=)\s*)`(?:\\[\s\S]|\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}|(?!\$\{)[^\\`])*`", lookbehind: true, greedy: true, inside: new Grammar
  {
      ["template-punctuation"] = new GrammarToken[]
      {

        new(@"^`|`$", lookbehind: false, greedy: false, alias: new []{"string" }),
      },
      ["embedded-code"] = new GrammarToken[]
      {

        new(@"[\s\S]+", lookbehind: false, greedy: false, alias: new []{"html" }),
      },
  }),
        new(@"((?:\bsvg)\s*)`(?:\\[\s\S]|\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}|(?!\$\{)[^\\`])*`", lookbehind: true, greedy: true, inside: new Grammar
  {
      ["template-punctuation"] = new GrammarToken[]
      {

        new(@"^`|`$", lookbehind: false, greedy: false, alias: new []{"string" }),
      },
      ["embedded-code"] = new GrammarToken[]
      {

        new(@"[\s\S]+", lookbehind: false, greedy: false, alias: new []{"svg" }),
      },
  }),
        new(@"((?:\b(?:markdown|md))\s*)`(?:\\[\s\S]|\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}|(?!\$\{)[^\\`])*`", lookbehind: true, greedy: true, inside: new Grammar
  {
      ["template-punctuation"] = new GrammarToken[]
      {

        new(@"^`|`$", lookbehind: false, greedy: false, alias: new []{"string" }),
      },
      ["embedded-code"] = new GrammarToken[]
      {

        new(@"[\s\S]+", lookbehind: false, greedy: false, alias: new []{"markdown" }),
      },
  }),
        new(@"((?:\b(?:gql|graphql(?:\s*\.\s*experimental)?))\s*)`(?:\\[\s\S]|\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}|(?!\$\{)[^\\`])*`", lookbehind: true, greedy: true, inside: new Grammar
  {
      ["template-punctuation"] = new GrammarToken[]
      {

        new(@"^`|`$", lookbehind: false, greedy: false, alias: new []{"string" }),
      },
      ["embedded-code"] = new GrammarToken[]
      {

        new(@"[\s\S]+", lookbehind: false, greedy: false, alias: new []{"graphql" }),
      },
  }),
        new(@"((?:\bsql)\s*)`(?:\\[\s\S]|\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}|(?!\$\{)[^\\`])*`", lookbehind: true, greedy: true, inside: new Grammar
  {
      ["template-punctuation"] = new GrammarToken[]
      {

        new(@"^`|`$", lookbehind: false, greedy: false, alias: new []{"string" }),
      },
      ["embedded-code"] = new GrammarToken[]
      {

        new(@"[\s\S]+", lookbehind: false, greedy: false, alias: new []{"sql" }),
      },
  }),
        new(@"`(?:\\[\s\S]|\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}|(?!\$\{)[^\\`])*`", lookbehind: false, greedy: true, inside: new Grammar
  {
      ["template-punctuation"] = new GrammarToken[]
      {

        new(@"^`|`$", lookbehind: false, greedy: false, alias: new []{"string" }),
      },
      ["interpolation"] = new GrammarToken[]
      {

        new(@"((?:^|[^\\])(?:\\{2})*)\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["interpolation-punctuation"] = new GrammarToken[]
      {

        new(@"^\$\{|\}$", lookbehind: false, greedy: false, alias: new []{"punctuation" }),
      },
      Reset = null! /* see below */,
  }),
      },
      ["string"] = new GrammarToken[]
      {

        new(@"[\s\S]+", lookbehind: false, greedy: false),
      },
  }),
      },
      ["string-property"] = new GrammarToken[]
      {

        new(new Regex(@"((?:^|[,{])[ \t]*)([""'])(?:\\(?:\r\n|[\s\S])|(?!\2)[^\\\r\n])*\2(?=\s*:)", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: true, alias: new []{"property" }),
      },
      ["string"] = new GrammarToken[]
      {
        null! /* see below */
      },
      ["class-name"] = new GrammarToken[]
      {

        new(@"(\b(?:class|extends|implements|instanceof|interface|new)\s+)[\w.\\]+", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[.\\]", lookbehind: false, greedy: false),
      },
  }),
        new(@"(^|[^$\w\xA0-\uFFFF])(?!\s)[_$A-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*(?=\.(?:constructor|prototype))", lookbehind: true, greedy: false),
      },
      ["regex"] = new GrammarToken[]
      {

        new(@"((?:^|[^$\w\xA0-\uFFFF.""'\])\s]|\b(?:return|yield))\s*)\/(?:(?:\[(?:[^\]\\\r\n]|\\.)*\]|\\.|[^/\\\[\r\n])+\/[dgimyus]{0,7}|(?:\[(?:[^[\]\\\r\n]|\\.|\[(?:[^[\]\\\r\n]|\\.|\[(?:[^[\]\\\r\n]|\\.)*\])*\])*\]|\\.|[^/\\\[\r\n])+\/[dgimyus]{0,7}v[dgimyus]{0,7})(?=(?:\s|\/\*(?:[^*]|\*(?!\/))*\*\/)*(?:$|[\r\n,.;:})\]]|\/\/))", lookbehind: true, greedy: true, inside: new Grammar
  {
      ["regex-source"] = new GrammarToken[]
      {

        new(@"^(\/)[\s\S]+(?=\/[a-z]*$)", lookbehind: true, greedy: false, alias: new []{"language-regex" }, inside: new Grammar
  {
      ["char-class"] = new GrammarToken[]
      {

        new(@"((?:^|[^\\])(?:\\\\)*)\[(?:[^\\\]]|\\[\s\S])*\]", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["char-class-negation"] = new GrammarToken[]
      {

        new(@"(^\[)\^", lookbehind: true, greedy: false, alias: new []{"operator" }),
      },
      ["char-class-punctuation"] = new GrammarToken[]
      {

        new(@"^\[|\]$", lookbehind: false, greedy: false, alias: new []{"punctuation" }),
      },
      ["range"] = new GrammarToken[]
      {

        new(@"(?:[^\\-]|\\(?:x[\da-fA-F]{2}|u[\da-fA-F]{4}|u\{[\da-fA-F]+\}|0[0-7]{0,2}|[123][0-7]{2}|c[a-zA-Z]|.))-(?:[^\\-]|\\(?:x[\da-fA-F]{2}|u[\da-fA-F]{4}|u\{[\da-fA-F]+\}|0[0-7]{0,2}|[123][0-7]{2}|c[a-zA-Z]|.))", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["escape"] = new GrammarToken[]
      {

        new(@"\\(?:x[\da-fA-F]{2}|u[\da-fA-F]{4}|u\{[\da-fA-F]+\}|0[0-7]{0,2}|[123][0-7]{2}|c[a-zA-Z]|.)", lookbehind: false, greedy: false),
      },
      ["range-punctuation"] = new GrammarToken[]
      {

        new(@"-", lookbehind: false, greedy: false, alias: new []{"operator" }),
      },
  }),
      },
      ["special-escape"] = new GrammarToken[]
      {

        new(@"\\[\\(){}[\]^$+*?|.]", lookbehind: false, greedy: false, alias: new []{"escape" }),
      },
      ["char-set"] = new GrammarToken[]
      {

        new(new Regex(@"\\[wsd]|\\p\{[^{}]+\}", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false, alias: new []{"class-name" }),
      },
      ["escape"] = new GrammarToken[]
      {

        new(@"\\(?:x[\da-fA-F]{2}|u[\da-fA-F]{4}|u\{[\da-fA-F]+\}|0[0-7]{0,2}|[123][0-7]{2}|c[a-zA-Z]|.)", lookbehind: false, greedy: false),
      },
  }),
      },
      ["special-escape"] = new GrammarToken[]
      {
        null! /* see below */
      },
      ["char-set"] = new GrammarToken[]
      {

        new(new Regex(@"\.|\\[wsd]|\\p\{[^{}]+\}", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false, alias: new []{"class-name" }),
      },
      ["backreference"] = new GrammarToken[]
      {

        new(@"\\(?![123][0-7]{2})[1-9]", lookbehind: false, greedy: false, alias: new []{"keyword" }),
        new(@"\\k<[^<>']+>", lookbehind: false, greedy: false, alias: new []{"keyword" }, inside: new Grammar
  {
      ["group-name"] = new GrammarToken[]
      {

        new(@"(<|')[^<>']+(?=[>']$)", lookbehind: true, greedy: false, alias: new []{"variable" }),
      },
  }),
      },
      ["anchor"] = new GrammarToken[]
      {

        new(@"[$^]|\\[ABbGZz]", lookbehind: false, greedy: false, alias: new []{"function" }),
      },
      ["escape"] = new GrammarToken[]
      {

        new(@"\\(?:x[\da-fA-F]{2}|u[\da-fA-F]{4}|u\{[\da-fA-F]+\}|0[0-7]{0,2}|[123][0-7]{2}|c[a-zA-Z]|.)", lookbehind: false, greedy: false),
      },
      ["group"] = new GrammarToken[]
      {

        new(@"\((?:\?(?:<[^<>']+>|'[^<>']+'|[>:]|<?[=!]|[idmnsuxU]+(?:-[idmnsuxU]+)?:?))?", lookbehind: false, greedy: false, alias: new []{"punctuation" }, inside: new Grammar
  {
      ["group-name"] = new GrammarToken[]
      {
        null! /* see below */
      },
  }),
        new(@"\)", lookbehind: false, greedy: false, alias: new []{"punctuation" }),
      },
      ["quantifier"] = new GrammarToken[]
      {

        new(@"(?:[+*?]|\{\d+(?:,\d*)?\})[?+]?", lookbehind: false, greedy: false, alias: new []{"number" }),
      },
      ["alternation"] = new GrammarToken[]
      {

        new(@"\|", lookbehind: false, greedy: false, alias: new []{"keyword" }),
      },
  }),
      },
      ["regex-delimiter"] = new GrammarToken[]
      {

        new(@"^\/|\/$", lookbehind: false, greedy: false),
      },
      ["regex-flags"] = new GrammarToken[]
      {

        new(@"^[a-z]+$", lookbehind: false, greedy: false),
      },
  }),
      },
      ["method-variable"] = new GrammarToken[]
      {

        new(@"(\.\s*)#?(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*(?=\s*[=:]\s*(?:async\s*)?(?:\bfunction\b|(?:\((?:[^()]|\([^()]*\))*\)|(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*)\s*=>))", lookbehind: true, greedy: false, alias: new []{"function-variable , method , function , property-access" }, inside: new Grammar
  {
      ["maybe-class-name"] = new GrammarToken[]
      {

        new(@"^[A-Z][\s\S]*", lookbehind: false, greedy: false),
      },
  }),
      },
      ["function-variable"] = new GrammarToken[]
      {

        new(@"#?(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*(?=\s*[=:]\s*(?:async\s*)?(?:\bfunction\b|(?:\((?:[^()]|\([^()]*\))*\)|(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*)\s*=>))", lookbehind: false, greedy: false, alias: new []{"function" }, inside: new Grammar
  {
      ["maybe-class-name"] = new GrammarToken[]
      {

        new(@"^[A-Z][\s\S]*", lookbehind: false, greedy: false),
      },
  }),
      },
      ["parameter"] = new GrammarToken[]
      {

        new(@"(function(?:\s+(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*)?\s*\(\s*)(?!\s)(?:[^()\s]|\s+(?![\s)])|\([^()]*\))+(?=\s*\))", lookbehind: true, greedy: false, inside: null! /* see below */),
        new(new Regex(@"(^|[^$\w\xA0-\uFFFF])(?!\s)[_$a-z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*(?=\s*=>)", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: true, greedy: false, inside: null! /* see below */),
        new(@"(\(\s*)(?!\s)(?:[^()\s]|\s+(?![\s)])|\([^()]*\))+(?=\s*\)\s*=>)", lookbehind: true, greedy: false, inside: null! /* see below */),
        new(@"((?:\b|\s|^)(?!(?:as|async|await|break|case|catch|class|const|continue|debugger|default|delete|do|else|enum|export|extends|finally|for|from|function|get|if|implements|import|in|instanceof|interface|let|new|null|of|package|private|protected|public|return|set|static|super|switch|this|throw|try|typeof|undefined|var|void|while|with|yield)(?![$\w\xA0-\uFFFF]))(?:(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*\s*)\(\s*|\]\s*\(\s*)(?!\s)(?:[^()\s]|\s+(?![\s)])|\([^()]*\))+(?=\s*\)\s*\{)", lookbehind: true, greedy: false, inside: null! /* see below */),
      },
      ["known-class-name"] = new GrammarToken[]
      {

        new(@"\b(?:(?:Float(?:32|64)|(?:Int|Uint)(?:8|16|32)|Uint8Clamped)?Array|ArrayBuffer|BigInt|Boolean|DataView|Date|Error|Function|Intl|JSON|(?:Weak)?(?:Map|Set)|Math|Number|Object|Promise|Proxy|Reflect|RegExp|String|Symbol|WebAssembly)\b", lookbehind: false, greedy: false, alias: new []{"class-name" }),
        new(@"\b(?:[A-Z]\w*)Error\b", lookbehind: false, greedy: false, alias: new []{"class-name" }),
      },
      ["constant"] = new GrammarToken[]
      {

        new(@"\b[A-Z](?:[A-Z_]|\dx?)*\b", lookbehind: false, greedy: false),
      },
      ["imports"] = new GrammarToken[]
      {

        new(@"(\bimport\b\s*)(?:(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*(?:\s*,\s*(?:\*\s*as\s+(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*|\{[^{}]*\}))?|\*\s*as\s+(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*|\{[^{}]*\})(?=\s*\bfrom\b)", lookbehind: true, greedy: false, inside: null! /* see below */),
      },
      ["exports"] = new GrammarToken[]
      {

        new(@"(\bexport\b\s*)(?:\*(?:\s*as\s+(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*)?(?=\s*\bfrom\b)|\{[^{}]*\})", lookbehind: true, greedy: false, inside: null! /* see below */),
      },
      ["keyword"] = new GrammarToken[]
      {

        new(@"\b(?:as|default|export|from|import)\b", lookbehind: false, greedy: false, alias: new []{"module" }),
        new(@"\b(?:await|break|catch|continue|do|else|finally|for|if|return|switch|throw|try|while|yield)\b", lookbehind: false, greedy: false, alias: new []{"control-flow" }),
        new(@"\bnull\b", lookbehind: false, greedy: false, alias: new []{"null , nil" }),
        new(@"\bundefined\b", lookbehind: false, greedy: false, alias: new []{"nil" }),
        new(@"((?:^|\})\s*)catch\b", lookbehind: true, greedy: false),
        new(@"(^|[^.]|\.\.\.\s*)\b(?:as|assert(?=\s*\{)|async(?=\s*(?:function\b|\(|[$\w\xA0-\uFFFF]|$))|await|break|case|class|const|continue|debugger|default|delete|do|else|enum|export|extends|finally(?=\s*(?:\{|$))|for|from(?=\s*(?:['""]|$))|function|(?:get|set)(?=\s*(?:[#\[$\w\xA0-\uFFFF]|$))|if|implements|import|in|instanceof|interface|let|new|null|of|package|private|protected|public|return|static|super|switch|this|throw|try|typeof|undefined|var|void|while|with|yield)\b", lookbehind: true, greedy: false),
      },
      ["boolean"] = new GrammarToken[]
      {

        new(@"\b(?:false|true)\b", lookbehind: false, greedy: false),
      },
      ["method"] = new GrammarToken[]
      {

        new(@"(\.\s*)#?(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*(?=\s*(?:\.\s*(?:apply|bind|call)\s*)?\()", lookbehind: true, greedy: false, alias: new []{"function , property-access" }, inside: new Grammar
  {
      ["maybe-class-name"] = new GrammarToken[]
      {

        new(@"^[A-Z][\s\S]*", lookbehind: false, greedy: false),
      },
  }),
      },
      ["function"] = new GrammarToken[]
      {

        new(@"#?(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*(?=\s*(?:\.\s*(?:apply|bind|call)\s*)?\()", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["maybe-class-name"] = new GrammarToken[]
      {

        new(@"^[A-Z][\s\S]*", lookbehind: false, greedy: false),
      },
  }),
      },
      ["number"] = new GrammarToken[]
      {
        null! /* see below */
      },
      ["literal-property"] = new GrammarToken[]
      {

        new(new Regex(@"((?:^|[,{])[ \t]*)(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*(?=\s*:)", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: false, alias: new []{"property" }),
      },
      ["spread"] = new GrammarToken[]
      {

        new(@"\.{3}", lookbehind: false, greedy: false, alias: new []{"operator" }),
      },
      ["arrow"] = new GrammarToken[]
      {

        new(@"=>", lookbehind: false, greedy: false, alias: new []{"operator" }),
      },
      ["operator"] = new GrammarToken[]
      {

        new(@"--|\+\+|\*\*=?|=>|&&=?|\|\|=?|[!=]==|<<=?|>>>?=?|[-+*/%&|^!=<>]=?|\.{3}|\?\?=?|\?\.?|[~:]", lookbehind: false, greedy: false),
      },
      ["property-access"] = new GrammarToken[]
      {

        new(@"(\.\s*)#?(?!\s)[_$a-zA-Z\xA0-\uFFFF](?:(?!\s)[$\w\xA0-\uFFFF])*", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["maybe-class-name"] = new GrammarToken[]
      {

        new(@"^[A-Z][\s\S]*", lookbehind: false, greedy: false),
      },
  }),
      },
      ["maybe-class-name"] = new GrammarToken[]
      {

        new(@"(^|[^$\w\xA0-\uFFFF])[A-Z][$\w\xA0-\uFFFF]+", lookbehind: true, greedy: false),
      },
      ["dom"] = new GrammarToken[]
      {

        new(@"\b(?:document|(?:local|session)Storage|location|navigator|performance|window)\b", lookbehind: false, greedy: false, alias: new []{"variable" }),
      },
      ["console"] = new GrammarToken[]
      {

        new(@"\bconsole(?=\s*\.)", lookbehind: false, greedy: false, alias: new []{"class-name" }),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[{}[\];(),.:]", lookbehind: false, greedy: false),
      },
  }),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"^=", lookbehind: false, greedy: false, alias: new []{"attr-equals" }),
        new(@"""|'", lookbehind: false, greedy: false),
      },
  }),
      },
  }),
      },
      ["attr-value"] = new GrammarToken[]
      {

        new(@"=\s*(?:""[^""]*""|'[^']*'|[^\s'"">=]+)", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"^=", lookbehind: false, greedy: false, alias: new []{"attr-equals" }),
        new(@"""|'", lookbehind: false, greedy: false),
      },
      ["entity"] = new GrammarToken[]
      {

        new(new Regex(@"&[\da-z]{1,8};", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false, alias: new []{"named-entity" }),
        new(new Regex(@"&#x?[\da-f]{1,8};", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false),
      },
  }),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\/?>", lookbehind: false, greedy: false),
      },
      ["attr-name"] = new GrammarToken[]
      {

        new(@"[^\s>\/]+", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["namespace"] = new GrammarToken[]
      {

        new(@"^[^\s>\/:]+:", lookbehind: false, greedy: false),
      },
  }),
      },
  }),
      },
      ["entity"] = new GrammarToken[]
      {

        null! /* see below */,
        new(new Regex(@"&#x?[\da-f]{1,8};", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false),
      },
      ["code"] = new GrammarToken[]
      {

        new(@".+", lookbehind: false, greedy: false, alias: new []{"language-java" }, inside: null! /* see below */),
      },
  }),
      },
  }),
      },
      ["tag"] = new GrammarToken[]
      {
        null! /* see below */
      },
      ["entity"] = new GrammarToken[]
      {

        null! /* see below */,
        new(new Regex(@"&#x?[\da-f]{1,8};", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false),
      },
      ["keyword"] = new GrammarToken[]
      {

        new(new Regex(@"(^[\t ]*(?:\/{3}|\*|\/\*\*)\s*|\{)@[a-z][a-zA-Z-]+\b", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[{}]", lookbehind: false, greedy: false),
      },
  },
  }),
    };
    grammar["comment"] = new GrammarToken[]
    {

        new(@"(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)", lookbehind: true, greedy: true),
        new(@"(^|[^\\:])\/\/.*", lookbehind: true, greedy: true),
    };
    grammar["triple-quoted-string"] = new GrammarToken[]
    {

        new(@"""""""[ \t]*[\r\n](?:(?:""|"""")?(?:\\.|[^""\\]))*""""""", lookbehind: false, greedy: true, alias: new []{"string" }),
    };
    grammar["char"] = new GrammarToken[]
    {

        new(@"'(?:\\.|[^'\\\r\n]){1,6}'", lookbehind: false, greedy: true),
    };
    grammar["string"] = new GrammarToken[]
    {

        new(@"(^|[^\\])""(?:\\.|[^""\\\r\n])*""", lookbehind: true, greedy: true),
    };
    grammar["annotation"] = new GrammarToken[]
    {

        new(@"(^|[^.])@\w+(?:\s*\.\s*\w+)*", lookbehind: true, greedy: false, alias: new []{"punctuation" }),
    };
    grammar["generics"] = new GrammarToken[]
    {

        new(@"<(?:[\w\s,.?]|&(?!&)|<(?:[\w\s,.?]|&(?!&)|<(?:[\w\s,.?]|&(?!&)|<(?:[\w\s,.?]|&(?!&))*>)*>)*>)*>", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["class-name"] = new GrammarToken[]
      {

        new(@"(^|[^\w.])(?:[a-z]\w*\s*\.\s*)*(?:[A-Z]\w*\s*\.\s*)*[A-Z](?:[\d_A-Z]*[a-z]\w*)?\b", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["namespace"] = new GrammarToken[]
      {

        new(@"^[a-z]\w*(?:\s*\.\s*[a-z]\w*)*(?:\s*\.)?", lookbehind: false, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
  }),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
  }),
      },
      ["keyword"] = new GrammarToken[]
      {

        new(@"\b(?:abstract|assert|boolean|break|byte|case|catch|char|class|const|continue|default|do|double|else|enum|exports|extends|final|finally|float|for|goto|if|implements|import|instanceof|int|interface|long|module|native|new|non-sealed|null|open|opens|package|permits|private|protected|provides|public|record(?!\s*[(){}[\]<>=%~.:,;?+\-*/&|^])|requires|return|sealed|short|static|strictfp|super|switch|synchronized|this|throw|throws|to|transient|transitive|try|uses|var|void|volatile|while|with|yield)\b", lookbehind: false, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"[<>(),.:]", lookbehind: false, greedy: false),
      },
      ["operator"] = new GrammarToken[]
      {

        new(@"[?&|]", lookbehind: false, greedy: false),
      },
  }),
    };
    grammar["import"] = new GrammarToken[]
    {

        new(@"(\bimport\s+)(?:[a-z]\w*\s*\.\s*)*(?:[A-Z]\w*\s*\.\s*)*(?:[A-Z]\w*|\*)(?=\s*;)", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["namespace"] = new GrammarToken[]
      {
        null! /* see below */
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
      ["operator"] = new GrammarToken[]
      {

        new(@"\*", lookbehind: false, greedy: false),
      },
      ["class-name"] = new GrammarToken[]
      {

        new(@"\w+", lookbehind: false, greedy: false),
      },
  }),
        new(@"(\bimport\s+static\s+)(?:[a-z]\w*\s*\.\s*)*(?:[A-Z]\w*\s*\.\s*)*(?:\w+|\*)(?=\s*;)", lookbehind: true, greedy: false, alias: new []{"static" }, inside: new Grammar
  {
      ["namespace"] = new GrammarToken[]
      {
        null! /* see below */
      },
      ["static"] = new GrammarToken[]
      {

        new(@"\b\w+$", lookbehind: false, greedy: false),
      },
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
      ["operator"] = new GrammarToken[]
      {

        new(@"\*", lookbehind: false, greedy: false),
      },
      ["class-name"] = new GrammarToken[]
      {

        new(@"\w+", lookbehind: false, greedy: false),
      },
  }),
    };
    grammar["namespace"] = new GrammarToken[]
    {

        new(@"(\b(?:exports|import(?:\s+static)?|module|open|opens|package|provides|requires|to|transitive|uses|with)\s+)(?!\b(?:abstract|assert|boolean|break|byte|case|catch|char|class|const|continue|default|do|double|else|enum|exports|extends|final|finally|float|for|goto|if|implements|import|instanceof|int|interface|long|module|native|new|non-sealed|null|open|opens|package|permits|private|protected|provides|public|record(?!\s*[(){}[\]<>=%~.:,;?+\-*/&|^])|requires|return|sealed|short|static|strictfp|super|switch|synchronized|this|throw|throws|to|transient|transitive|try|uses|var|void|volatile|while|with|yield)\b)[a-z]\w*(?:\.[a-z]\w*)*\.?", lookbehind: true, greedy: false, inside: new Grammar
  {
      ["punctuation"] = new GrammarToken[]
      {

        new(@"\.", lookbehind: false, greedy: false),
      },
  }),
    };
    grammar["class-name"] = new GrammarToken[]
    {

        null! /* see below */,
        new(@"(^|[^\w.])(?:[a-z]\w*\s*\.\s*)*(?:[A-Z]\w*\s*\.\s*)*[A-Z]\w*(?=\s+\w+\s*[;,=()]|\s*(?:\[[\s,]*\]\s*)?::\s*new\b)", lookbehind: true, greedy: false, inside: null! /* see below */),
        new(@"(\b(?:class|enum|extends|implements|instanceof|interface|new|record|throws)\s+)(?:[a-z]\w*\s*\.\s*)*(?:[A-Z]\w*\s*\.\s*)*[A-Z]\w*\b", lookbehind: true, greedy: false, inside: null! /* see below */),
    };
    grammar["keyword"] = new GrammarToken[]
    {

        new(@"\b(?:abstract|assert|boolean|break|byte|case|catch|char|class|const|continue|default|do|double|else|enum|exports|extends|final|finally|float|for|goto|if|implements|import|instanceof|int|interface|long|module|native|new|non-sealed|null|open|opens|package|permits|private|protected|provides|public|record(?!\s*[(){}[\]<>=%~.:,;?+\-*/&|^])|requires|return|sealed|short|static|strictfp|super|switch|synchronized|this|throw|throws|to|transient|transitive|try|uses|var|void|volatile|while|with|yield)\b", lookbehind: false, greedy: false),
    };
    grammar["boolean"] = new GrammarToken[]
    {

        new(@"\b(?:false|true)\b", lookbehind: false, greedy: false),
    };
    grammar["function"] = new GrammarToken[]
    {

        new(@"\b\w+(?=\()", lookbehind: false, greedy: false),
        new(@"(::\s*)[a-z_]\w*", lookbehind: true, greedy: false),
    };
    grammar["number"] = new GrammarToken[]
    {

        new(new Regex(@"\b0b[01][01_]*L?\b|\b0x(?:\.[\da-f_p+-]+|[\da-f_]+(?:\.[\da-f_p+-]+)?)\b|(?:\b\d[\d_]*(?:\.[\d_]*)?|\B\.\d[\d_]*)(?:e[+-]?\d[\d_]*)?[dfl]?", RegexOptions.Compiled | RegexOptions.IgnoreCase), lookbehind: false, greedy: false),
    };
    grammar["operator"] = new GrammarToken[]
    {

        new(new Regex(@"(^|[^.])(?:<<=?|>>>?=?|->|--|\+\+|&&|\|\||::|[?:~]|[-+*/%&|^!=<>]=?)", RegexOptions.Compiled | RegexOptions.Multiline), lookbehind: true, greedy: false),
    };
    grammar["punctuation"] = new GrammarToken[]
    {

        new(@"[{}[\];(),.:]", lookbehind: false, greedy: false),
    };
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][0].Inside!["code"][0].Inside = grammar;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][0].Inside!["attr-value"][0].Inside!["value"][0].Inside!["atrule"][0].Inside!.Reset = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][0].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][0].Inside!["attr-value"][0].Inside!["value"][0].Inside!["selector"][0].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][0].Inside!["attr-value"][0].Inside!["value"][0].Inside!["atrule"][0].Inside!["selector-function-argument"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][0].Inside!["attr-value"][0].Inside!["value"][0].Inside!["unit"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][0].Inside!["attr-value"][0].Inside!["value"][0].Inside!["color"][1].Inside!["unit"][0];
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][0].Inside!["attr-value"][0].Inside!["value"][0].Inside!["number"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][0].Inside!["attr-value"][0].Inside!["value"][0].Inside!["color"][1].Inside!["number"][0];
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["doc-comment"][0].Inside!.Reset!["optional-parameter"][0].Inside!["code"][0].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["doc-comment"][0].Inside!.Reset!["example"][0].Inside!["code"][0].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["template-string"][6].Inside!["interpolation"][0].Inside!.Reset = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["string"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["doc-comment"][0].Inside!.Reset!["class-name"][1].Inside!["string"][0];
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["regex"][0].Inside!["regex-source"][0].Inside!["special-escape"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["regex"][0].Inside!["regex-source"][0].Inside!["char-class"][0].Inside!["special-escape"][0];
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["regex"][0].Inside!["regex-source"][0].Inside!["group"][0].Inside!["group-name"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["regex"][0].Inside!["regex-source"][0].Inside!["backreference"][1].Inside!["group-name"][0];
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["parameter"][0].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["parameter"][1].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["parameter"][2].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["parameter"][3].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["imports"][0].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["exports"][0].Inside = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!;
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["number"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["special-attr"][1].Inside!["attr-value"][0].Inside!["value"][0].Inside!["doc-comment"][0].Inside!.Reset!["class-name"][1].Inside!["number"][0];
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["entity"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["attr-value"][0].Inside!["entity"][0];
    grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["code"][0].Inside = grammar;
    grammar["doc-comment"][0].Inside!.Reset!["tag"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0];
    grammar["doc-comment"][0].Inside!.Reset!["entity"][0] = grammar["doc-comment"][0].Inside!.Reset!["code-section"][1].Inside!["line"][0].Inside!["tag"][0].Inside!["attr-value"][0].Inside!["entity"][0];
    grammar["import"][0].Inside!["namespace"][0] = grammar["generics"][0].Inside!["class-name"][0].Inside!["namespace"][0];
    grammar["import"][1].Inside!["namespace"][0] = grammar["generics"][0].Inside!["class-name"][0].Inside!["namespace"][0];
    grammar["class-name"][0] = grammar["generics"][0].Inside!["class-name"][0];
    grammar["class-name"][1].Inside = grammar["generics"][0].Inside!["class-name"][0].Inside!;
    grammar["class-name"][2].Inside = grammar["generics"][0].Inside!["class-name"][0].Inside!;

    return grammar;
  }
}
